services:
  fs-app:
    container_name: fs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3100:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:FundS1ght@2026@fs-postgres:5432/fundsight
      - NEXTAUTH_SECRET=k8mRvX2pLwQ9nYjT4bHs7dFcA1eZuG6o
      - NEXTAUTH_URL=https://fundsight.karetechsolutions.com
      - AUTH_TRUST_HOST=true
    depends_on:
      fs-postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - fundsight-network

  fs-postgres:
    container_name: fs-postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: FundS1ght@2026
      POSTGRES_DB: fundsight
    volumes:
      - fs_postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - fundsight-network

volumes:
  fs_postgres_data:

networks:
  fundsight-network:
    driver: bridge
